import { useState, type ReactNode } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { Sparkles, RefreshCw, Film, Tv, Info, Zap } from "lucide-react";

import { ContentCard } from "@/components/ContentCard";
import { ContentGridSkeleton } from "@/components/Skeletons";
import { EmptyState, ErrorState } from "@/components/States";
import { Button } from "@/components/ui/button";
import { recommendationService } from "@/services/recommendations";
import { catalogService } from "@/services/catalog";
import { useAuthStore } from "@/store/authStore";
import { cn } from "@/lib/utils";

export function RecommendationPage() {
  const user = useAuthStore((s) => s.user);
  const queryClient = useQueryClient();
  const [contentType, setContentType] = useState<"all" | "movie" | "tv">("all");
  const [refreshNotice, setRefreshNotice] = useState("");

  // Fetch recommendations for authenticated users
  const recQuery = useQuery({
    queryKey: ["recommendations", "catalog", contentType, user?.id],
    queryFn: () =>
      recommendationService.getRecommendations({
        contentType,
        limit: 20,
      }),
    enabled: Boolean(user),
  });

  // Fallback trending/popular for non-authenticated guests
  const guestQuery = useQuery({
    queryKey: ["guestRecommendations", contentType],
    queryFn: () =>
      catalogService.getTrending({
        type: contentType,
        timeWindow: "week",
      }),
    enabled: !user,
  });

  const refreshMutation = useMutation({
    mutationFn: () => recommendationService.refresh(),
    onSuccess: () => {
      setRefreshNotice("Recommendations regenerated based on your latest activity.");
      queryClient.invalidateQueries({ queryKey: ["recommendations"] });
      setTimeout(() => setRefreshNotice(""), 5000);
    },
    onError: () => {
      setRefreshNotice("Could not refresh pipeline right now. Serving cached recommendations.");
      setTimeout(() => setRefreshNotice(""), 5000);
    },
  });

  const isLoading = user ? recQuery.isLoading : guestQuery.isLoading;
  const isError = user ? recQuery.isError : guestQuery.isError;
  const error = user ? recQuery.error : guestQuery.error;
  const refetch = () => (user ? recQuery.refetch() : guestQuery.refetch());

  const items = user ? recQuery.data?.items || [] : guestQuery.data || [];

  // Cold-start detection: the backend's fallback path stamps every item with a
  // `cold_start_popularity` source when the recommendation engine lacks enough
  // signal for this user. We never fabricate personalization — we surface the
  // real engine state instead. (Threshold lives server-side, not in React.)
  const recItems = user ? (recQuery.data?.items ?? []) : [];
  const isColdStart =
    Boolean(user) &&
    recItems.length > 0 &&
    recItems.some((it) => (it.sources ?? []).some((s) => s.includes("cold_start")));

  // Personalized only once real signal exists; otherwise keep the generic title.
  const isPersonalized = Boolean(user) && recItems.length > 0 && !isColdStart;
  const displayName =
    user?.full_name?.trim() ||
    user?.username?.trim() ||
    (user?.email ? user.email.split("@")[0] : "");
  const pageTitle =
    isPersonalized && displayName ? `${displayName}, You May Like` : "Personalized Recommendations";

  const typeTabs: { key: "all" | "movie" | "tv"; label: string; icon?: ReactNode }[] = [
    { key: "all", label: "All Recommendations" },
    { key: "movie", label: "Movies Only", icon: <Film size={13} aria-hidden="true" /> },
    { key: "tv", label: "Web Series Only", icon: <Tv size={13} aria-hidden="true" /> },
  ];

  return (
    <div className="mx-auto max-w-[1400px] px-4 py-8 sm:px-7">
      {/* Hero header */}
      <header className="mb-6">
        <div className="mb-1.5 flex items-center gap-2">
          <Sparkles size={18} className="text-primary" aria-hidden="true" />
          <span className="text-[11px] font-extrabold uppercase tracking-[0.16em] text-primary/80">
            Hybrid AI Pipeline
          </span>
        </div>
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
              {pageTitle}
            </h1>
            <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
              {isPersonalized
                ? "Generated by WatchMan's hybrid engine from your saves, likes, ratings, and watch history."
                : "Vector embeddings, collaborative filtering, and taste profiling tailored to your watchlist."}
            </p>
          </div>

          {user && (
            <Button
              type="button"
              variant="brand"
              onClick={() => refreshMutation.mutate()}
              disabled={refreshMutation.isPending}
            >
              <RefreshCw
                size={16}
                aria-hidden="true"
                className={refreshMutation.isPending ? "animate-spin" : ""}
              />
              {refreshMutation.isPending ? "Recalculating…" : "Refresh Feed"}
            </Button>
          )}
        </div>
      </header>

      {/* Guest notice */}
      {!user && (
        <div className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-primary/30 bg-gradient-to-r from-primary/10 to-primary/5 px-5 py-4">
          <div className="flex items-center gap-3">
            <Zap size={22} className="shrink-0 text-primary" aria-hidden="true" />
            <div>
              <strong className="text-sm font-semibold text-foreground">
                Unlock personalized AI recommendations
              </strong>
              <p className="mt-0.5 text-[13px] text-muted-foreground">
                Sign in to train your personalized taste profile and get recommendations matching
                your tastes.
              </p>
            </div>
          </div>
          <Button asChild variant="brand" size="sm" className="shrink-0">
            <Link to="/login">Sign in</Link>
          </Button>
        </div>
      )}

      {/* Refresh notice */}
      {refreshNotice && (
        <div
          role="status"
          aria-live="polite"
          className="mb-5 rounded-lg border border-primary/30 bg-primary/10 px-4 py-2.5 text-sm text-foreground"
        >
          {refreshNotice}
        </div>
      )}

      {/* Type filter tabs */}
      <div
        role="tablist"
        aria-label="Recommendation type"
        className="mb-6 flex flex-wrap gap-2 border-b border-border pb-4"
      >
        {typeTabs.map((tab) => {
          const active = contentType === tab.key;
          return (
            <button
              key={tab.key}
              type="button"
              role="tab"
              aria-selected={active}
              onClick={() => setContentType(tab.key)}
              className={cn(
                "inline-flex items-center gap-1.5 rounded-full border px-4 py-1.5 text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
                active
                  ? "border-transparent bg-brand-gradient text-watchman-black"
                  : "border-border bg-secondary text-muted-foreground hover:bg-accent hover:text-foreground",
              )}
            >
              {tab.icon}
              {tab.label}
            </button>
          );
        })}
      </div>

      {/* Content grid */}
      {isLoading ? (
        <ContentGridSkeleton count={16} />
      ) : isError ? (
        <ErrorState error={error} onRetry={refetch} />
      ) : isColdStart ? (
        <>
          {/* Cold-start: the engine has no personalized signal yet. We say so
              honestly and explain how the user builds it up — no fake personalization. */}
          <div className="mb-8 rounded-2xl border border-primary/30 bg-gradient-to-r from-primary/10 to-primary/5 px-6 py-6">
            <div className="flex items-start gap-3">
              <Sparkles size={22} className="mt-0.5 shrink-0 text-primary" aria-hidden="true" />
              <div>
                <h2 className="text-lg font-semibold text-foreground">
                  Recommendations will appear as you explore WatchMan
                </h2>
                <p className="mt-1.5 max-w-2xl text-sm text-muted-foreground">
                  Your personalized feed gets smarter as the engine learns your taste. It improves
                  each time you:
                </p>
                <ul className="mt-3 grid gap-1.5 text-sm text-muted-foreground sm:grid-cols-2">
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-primary" aria-hidden="true" />
                    View a movie or web series
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-primary" aria-hidden="true" />
                    Like titles you enjoy
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-primary" aria-hidden="true" />
                    Save titles to your list
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-primary" aria-hidden="true" />
                    Rate and review what you&apos;ve seen
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-primary" aria-hidden="true" />
                    Build up your watch history
                  </li>
                </ul>
                <div className="mt-4 flex flex-wrap gap-2">
                  <Button asChild variant="brand" size="sm">
                    <Link to="/trending">Explore trending</Link>
                  </Button>
                  <Button asChild variant="outline" size="sm">
                    <Link to="/profile">Set preferred genres</Link>
                  </Button>
                </div>
              </div>
            </div>
          </div>

          {/* Real, popularity-based picks to get started — explicitly NOT presented
              as personalized. These are genuine TMDB-popular titles, never fabricated. */}
          <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted-foreground">
            Popular on WatchMan to get you started
          </h2>
          <ul className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">
            {items.map((item) => (
              <li
                key={`${item.content_type || (contentType === "tv" ? "tv" : "movie")}-${item.id || item.tmdb_id}`}
              >
                <ContentCard content={item as any} />
              </li>
            ))}
          </ul>
        </>
      ) : items.length > 0 ? (
        <>
          <ul className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">
            {items.map((item) => (
              <li
                key={`${item.content_type || (contentType === "tv" ? "tv" : "movie")}-${item.id || item.tmdb_id}`}
              >
                <ContentCard content={item as any} />
              </li>
            ))}
          </ul>

          {user && (
            <div className="mt-10 flex items-center gap-3 rounded-xl border border-border bg-card/50 px-5 py-4 text-[13px] text-muted-foreground">
              <Info size={18} className="shrink-0 text-primary" aria-hidden="true" />
              <span>
                Want to refine these recommendations? Rate titles you&apos;ve watched, mark
                favorites, or set preferred genres in{" "}
                <Link to="/profile" className="font-medium text-primary hover:underline">
                  your Profile
                </Link>
                .
              </span>
            </div>
          )}
        </>
      ) : (
        <EmptyState
          title="No recommendations found yet"
          description="Start exploring trending movies and web series and rate titles to train your recommendation model."
          action={
            <Button asChild variant="brand" size="sm">
              <Link to="/trending">Explore trending</Link>
            </Button>
          }
        />
      )}
    </div>
  );
}
